### PR TITLE
added BigInteger brute force

### PR DESCRIPTION
**Pull request by tonetheman**
I added BigInteger brute force.

### CODE REVIEW

**Comment by choyiny** [comment]
can you name it a different function

#3

**Comment by tonetheman** [comment]
Sure no problem... what name were you wanting? Or do you have a suggestion?

**Comment by choyiny** [comment]
just to differentiate it and my original function.

**Comment by tonetheman** [comment]
I renamed the method in my last commit. I added a BI to the end in hopes of making it clear it was a BigInteger.

**Comment by choyiny** [comment]
Yep that works, but can you solve merge conflicts? thanks.

**Comment by tonetheman** [comment]
cool cool all done. thanks!

**Comment by choyiny** [comment]
Merged, thanks!

**Pull request merged**
