### PR TITLE
removed unneccessary files

### PR DESCRIPTION
**Pull request by arpit1997**
removed .gitignore's files 
reference issue #12

### CODE REVIEW

**Comment by choyiny** [comment]
will this also remove the files in my end?

**Comment by arpit1997** [comment]
yeah merging this would remove files on your end too.

**Comment by choyiny** [comment]
is there a way to not do that?

**Comment by arpit1997** [comment]
yeah don't merge the PR :smiley:

**Comment by choyiny** [comment]
But I don't want the project files to exist in the repo.

**Comment by arpit1997** [comment]
well you should not have pushed these files on Github in the first place. Even if you did that you should delete these since it is not required for VCS. Deleting these files would not affect your project

**Comment by choyiny** [comment]
Merged, thanks.

**Comment by arpit1997** [comment]
you're welcome. My pleasure

**Pull request merged**
