### PR TITLE
Added a JOptionPane to input semiPrimes

### PR DESCRIPTION
**Pull request by mileschandler**
Added a JOptionPane to input semiprimes and checks for invalid input exceptions.

### CODE REVIEW

**Comment by choyiny** [comment]
Can you provide a screenshot for your work? #4

**Comment by mileschandler** [comment]
semiprimescnshotproof

not sure what you mean.

**Comment by choyiny** [comment]
Screenshot the GUI I meant 😂

**Comment by mileschandler** [comment]
guiscrnshot

Haha sorry
Thought you said "of your work"

**Comment by choyiny** [comment]
Merged. If you want to try the full fledged GUI? 📦

**Comment by mileschandler** [comment]
Ill hack at it tomorrow. Give me more info on what you would life it to look like?

**Pull request merged**
